server.port: 9443
spring.profiles: default
demo.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://svlada.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
  
spring.datasource:
  url: "jdbc:mysql://localhost:3306/oauth2"
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: vijay
spring.jpa:
  database-platform: org.hibernate.dialect.MySQLDialect
spring.h2.console.enabled: true

server.ssl.key-store: classpath:keystore.jks
server.ssl.key-store-password: pass123
server.ssl.key-password: pass123